couchbase/couchbase-lite-java

- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
This is companion PR for https://github.com/couchbase/couchbase-lite-java-core/pull/517
- If user uses latest version of SQLite, this does not require. For older version of SQLite, we need to implement this to avoid crash issue in `View.updateIndex()`
> Added `isNull(int)` for `Cursor` implementation for fixing Java Core 497

- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
Called Key.derivePBKDF2SHA256Key() method implemented in couchbase-lite-java-sqlcipher to do key derivation using libcrypto.
https://github.com/couchbase/couchbase-lite-java-core/issues/805
> Implement key derivation using libcrypto

- build.gradle
- `couchbase-lite-java-javascript` was not set as test dependency.
> Fixed #98 - CBL Java build failure on Jenkins

- src/main/cpp/native_c4document.cc
- src/main/cpp/native_encoder.cc
- src/main/cpp/native_fleece.cc
- src/main/cpp/native_glue.cc
- src/main/cpp/native_glue.hh
- src/main/java/com/couchbase/lite/LiveQuery.java
- src/main/java/com/couchbase/lite/internal/fleece/AllocSlice.java
- src/main/java/com/couchbase/lite/internal/fleece/Encoder.java
- src/main/java/com/couchbase/lite/internal/fleece/FLValue.java
This should fix https://issues.couchbase.com/browse/CBSE-6741
The new strategy for UTF-8/JString conversion is just to avoid Modified UTF-8 all together.  Use C++ conversion functions to convert UTF-8 <> UTF-16 and leave the rest to Java
> New strategy for converting UTF-8 to JString and back.

- src/main/java/com/couchbase/lite/AbstractDatabase.java
- src/main/java/com/couchbase/lite/ConflictResolver.java
- src/main/java/com/couchbase/lite/Document.java
* Renamed Document.getRevID() to getRevisionID() and made it public.
* Refactored the code due to method name change accordingly.
> Make Document.getRevisionID() public API (CBL-150)

- src/ce/java/com/couchbase/lite/ConsoleLogger.java
- src/main/java/com/couchbase/lite/AbstractConsoleLogger.java
- src/main/java/com/couchbase/lite/LogLevel.java
* Extracted shared logic b/w Android and Java ConsoleLogger into AbstractConsoleLogger class.
* Implemented ConsoleLogger for Java by writing logs to System.out or System.err for errors.
* Added toString() implementation to LogLevel; the returned strings are inline to what Android’s log levels are printed to LogCat.
> Implement ConsoleLogger for Java (CBL-166)

- build.gradle
- scripts/prebuild_macos.sh
* Add native build to build.gradle (only for MacOS); the native library will be installed at `libs/osx/x86_64` in the jar file.
* Add prebuild_macos.sh script to prebuild lite-core libraries for MacOS
> Add MacOS native build to build.gradle (CBL-158)

- src/ce/java/com/couchbase/lite/CouchbaseLite.java
- src/ce/java/com/couchbase/lite/NativeLibraryLoader.java
* Native libraries including CBL-JNI and LiteCore shared library will be extracted to system-temp-director/com.couchbase.lite.java and being loaded from that location.
* If there is an existing library, NativeLibraryLoader will simply delete the existing ones first. We can enhance this later to also check whether the existing and the new ones are the same (e.g. using MD5).
* Implemented CouchbaseLite class except getExecutionService() method which will be done in separated commit.
> Implement NativeLibraryLoader and CouchbaseLite for Java (CBL-161)

- scripts/prebuild_windows.bat
- src/shared/test/java/com/couchbase/lite/EncodingTest.java
* 1st 4 byte char and 2nd is legal. But 3rd char is not legal without preceding a 4byte char similar to the 1st.
* somehow windows is allowing this.
previous PR is not behaving nicely: link #129
> fix: encoding test with UTF8

- src/main/java/com/couchbase/lite/AbstractDatabase.java
Push the `copy` method down out of the API, so that the EE methods can use encryption as required.
> Fix for CBl-48: Fail copying an encrypted DB

- src/main/java/com/couchbase/lite/internal/JavaExecutionService.java
- src/shared/test/java/com/couchbase/lite/internal/ExecutionServicesTest.kt
* corrected the main executor to use single thread executor
* corrected the timing for windows, since it takes 20milli-seconds extra to load and execute the task. 777 delay will turn to 797 delay in current windows machine.
> CBL-223: fix: main executor was using thread pool

- src/shared/test/java/com/couchbase/lite/internal/core/C4BaseTest.java
* previously it was not converting the read bytes to UTF8 when passing to the encodeJSON.
> CBL-224: fix: default charset was chosen when getting bytes, and input stream

- src/shared/main/java/com/couchbase/lite/internal/AbstractExecutionService.java
- src/shared/test/java/com/couchbase/lite/internal/ExecutionServicesTest.kt
* The concurrent executor is shared so it is needed to be restarted when tests stop it. The issue didn’t happen on CBL Android because somehow the CBL Android tests get executed in an order that doesn’t cause the problem.
* Added AbstractExecutorService’s restartConcurrentExecutor() method that will call the restart() method of the ConcurrentExecutor.
> CBL-273 : Add an internal API for restarting concurrent executor

- src/shared/main/java/com/couchbase/lite/CBLError.java
- src/shared/main/java/com/couchbase/lite/LogFileConfiguration.java
- src/shared/main/java/com/couchbase/lite/internal/support/Log.java
- src/shared/test/java/com/couchbase/lite/LogTest.java
The standard error messages are now available.  Just need to find them and use them.
> CBL-442 (partial): enable standard error messages

- src/shared/main/cpp/native_c4blobstore.cc
- src/shared/main/cpp/native_glue.cc
- src/shared/main/cpp/native_glue.hh
- src/shared/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java
There is way too much copying of large arrays, when managing blobs.  This method should reduce the number of copies by one.
> Add write with length for BlobStream

- etc/jenkins/README.md
Added REAME explaining how to use the Jenkins build script to build and package couchbase-lite-java.
> Add README for Jenkins build scripts

- lib/src/main/java/com/couchbase/lite/internal/JavaExecutionService.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/ReplicatorChangeListenerToken.java
- lib/src/shared/main/java/com/couchbase/lite/internal/AbstractExecutionService.java
- lib/src/shared/main/java/com/couchbase/lite/internal/ExecutionService.java
- lib/src/shared/main/java/com/couchbase/lite/internal/support/Log.java
- lib/src/shared/test/java/com/couchbase/lite/ConcurrencyTest.java
This change adds task diagnostics to the CBL thread manager.  On catastrophic failures, it will log useful information helpful for identifying the cause of the failure
> Add thread diagnostics

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/FileLogger.java
- lib/src/shared/main/java/com/couchbase/lite/internal/support/Log.java
- lib/src/shared/test/java/com/couchbase/lite/BaseTest.java
Fix inconsistent log levels for bindings and core.  We trust the bindings.
> CBL-497: getLogLevel changes log level

- lib/build.gradle
* Generated MD5 file for each native library; the MD5 will be used (later) to figure out the location to extract native libraries from jar file.
* Fixed Lite-Core libs could be copied into a wrong location.
> Generate MD5 for each native library

- lib/src/main/java/com/couchbase/lite/NativeLibrary.java
* Extracted the native library into <temp>/com.couchbase.lite.java/native/<MD5>.
* The MD5 hash is the MD5 of the combined MD5 of all native libraries to be extracted.
> Rework NativeLibrary to extract the libs into an MD5 hash directory

- lib/src/shared/main/java/com/couchbase/lite/Blob.java
- lib/src/shared/test/java/com/couchbase/lite/BlobTest.java
My apologies, this is essentially another re-write.  I think you will do best simply to read the code, not the diffs.
All tests (android and java) pass.  ... and I think I've annoyed everyone with the details of this more-or-less unused feature, so that it implements something close to what iOS and .NET implement... warts and all.
Read the test code only if you are a masochist...
> Make Java blobs work like .NET blobs

- etc/jenkins/build_windows.bat
- lib/build.gradle
- lib/src/shared/main/cpp/native_glue.cc
* Using /MD when building JNI using Windows
* Disabled style check for windows by creating ciCheckWindows.
* Added a workaround for std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t>() undefined when using Visual Studio to build
> Fix windows build when using Visual Studio 2015

- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4BlobReadStream.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java
- Fixed blob stream not getting close in C4BlobReadStream.close() and C4BlobWriteStream.close() method.
- This issue was uncovered when running the unit tests on Windows as the database cannot be deleted if there is something still holding on to it.
> Fix blob read and write stream not getting closed

- src/main/cpp/native_c4replicator.cc
I have noticed from debugging that the local references may not get cleaned up immediately after the native method returns. As a result, there could be a lot of local references from a large set of document ended gets pilling up in the table to cause the overflow. This commit manually cleans up the local references after done using them.
Ref: CBSE-7597
> Cleanup document ended local references after using them

- lib/src/main/java/com/couchbase/lite/internal/JavaExecutionService.java
- lib/src/shared/main/java/com/couchbase/lite/internal/AbstractExecutionService.java
- lib/src/shared/main/java/com/couchbase/lite/internal/ExecutionService.java
- lib/src/shared/test/java/com/couchbase/lite/internal/ExecutionServiceTest.kt
- lib/src/shared/test/java/com/couchbase/lite/internal/ExecutionServicesTest.kt
There are two important changes, here:
1) The parallel executor will never use the last MIN_CAPACITY (currently 64) slots of a bounded executor queue.  That leave a fair amount of space for serial queues (2 slots per queue) and other application stuff.
2) When the parallel executor exhausts execution resources (availCapacity - MIN_CAPACITY <= 0) it fails over to using an unbounded serial queue.  This means that the failure mode for, e.g., conflict revolvers that permanently block all execution, will be an eventual OOM.  Before the OOM warnings will be logged to help identify the actual problem.  Unfortunately, though, because the queue is unbounded, there will be no helpful execution queue dump.
All tests passing on all platforms
> Concurrent executor failover to serial queue

- etc/jenkins/build_linux.sh
- lib/build.gradle
- scripts/build_litecore.sh
- Support libc++ library deployed at a custom location.
- Allow to build mbedcrypto by using its cmake directly without going through LiteCore's cmake.
- Enable DCMAKE_POSITION_INDEPENDENT_CODE when directly cmaking mbedcryoto.
Note: 
1. The two commits has been cherry-picked from the master.
2. The fix has been verified as the linux build on Jenkins is now successful.
Reference: https://issues.couchbase.com/browse/CBL-571
> CBL-571 : Fix linux build issue on Jenkins

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
It seems like localDoc could be collected before the end of saveResolvedDocument(). The speculation is that the JIT optimizer might think that localDoc hasn’t been used anymore after the line that gets the rawDoc (C4Document) from the localDoc so it could be collected.
From repeatedly running the test, this little trick by trying to use the localDoc until the end could help keeping the localDoc alive until the end. 
Reference: https://issues.couchbase.com/browse/CBL-583
> CBL-583: Prevent localDoc object to be collected

- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Document.java
- lib/src/shared/main/java/com/couchbase/lite/internal/support/Log.java
- lib/src/shared/main/java/com/couchbase/lite/utils/Fn.java
- lib/src/shared/test/java/com/couchbase/lite/LogTest.java
While we did not succeed in root-causing CBL-583, it is pretty clear what the problem was: the C4Document code was wildly non-thread-safe.  This code should make it thread-safe and also corrects some loosey-goosey visibility.
This is another near-rewrite.  It might make more sense to just read the code, than to try to read the diffs.
I am currently developing a minimal subset of this change, for Mercury.
> Thread-safe C4Document

- lib/src/main/java/com/couchbase/lite/CouchbaseLite.java
- lib/src/main/java/com/couchbase/lite/internal/CouchbaseLiteInternal.java
- lib/src/main/java/com/couchbase/lite/internal/NativeLibrary.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/ChangeListenerToken.java
- lib/src/shared/main/java/com/couchbase/lite/DocumentExpirationStrategy.java
- lib/src/shared/main/java/com/couchbase/lite/Log.java
- lib/src/shared/main/java/com/couchbase/lite/ReplicatorChangeListenerToken.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Document.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Log.java
- lib/src/shared/test/java/com/couchbase/lite/BaseTest.java
- lib/src/shared/test/java/com/couchbase/lite/PreInitTest.java
- lib/src/shared/test/java/com/couchbase/lite/ReplicatorChangeListenerTokenTest.java
- lib/src/shared/test/java/com/couchbase/lite/internal/ExecutionServiceTest.kt
- lib/src/test/java/com/couchbase/lite/PlatformBaseTest.java
Move most of CouchbaseLite to CouchbaseLiteInternal hiding CouchbaseLite.getExecutionService()
This is a coordinated update with the other three java family products. There are five changes:
1) move most functionality from CouchbaseLite to CouchbaseLiteInternal
2) rename references to CouchbaseLite to CouchbaseLiteInternal
3) move NativeLibrary to make it visible to CBLInternal
4) Add a debug flag in CBLInternal
5) Add debug-flag controlled release info to C4Document
> CBL-164: Move CouchbaseLite.getExecutionService() out of the public API

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/DocContext.java
- lib/src/shared/main/java/com/couchbase/lite/Document.java
- lib/src/shared/main/java/com/couchbase/lite/QueryChange.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Database.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Document.java
- lib/src/shared/test/java/com/couchbase/lite/QueryTest.java
- lib/src/shared/test/java/com/couchbase/lite/ReplicatorOfflineTest.java
This is a big PR.  Sorry.
The main change is that C4Document is no longer RefCounted.
In addition its finalizer no longer attempts to seize a lock (which may already have been GCed)
This change causes changes in other files:
- DocContext no longer manages the C4Document
- AbstractDatabase no longer manages the C4Document
- Document no longer manages the C4Document
In addition Document no longer needs `free` and `finalizer`
Also now closer to thread safe
- `shouldRetain` in C4Database is now final
its finalizer no longer attempts to seize locks.  See above
- QueryChange gets some purely cosmetic changes
> Change memory management strategy for C4Document (CBL-601)

- etc/jenkins/build_linux.sh
- etc/jenkins/publish.sh
Fix the ProGet URL, embedded in the build scripts.
Note that this will be merged to the head of release/android/mercury.
> Fix ProGet URL
