- src/main/java/com/couchbase/lite/util/LoggerImpl.java
- src/main/java/com/couchbase/lite/util/SimpleLogger.java
> Eliminated getResourceAsStream() to minimize memory usage 

- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
- Implement insertOrThrow method on JavaSQLiteStorageEngine.
- On JavaSQLiteStorageEngine, catching the com.couchbase.lite.data.SQLException instead the generic exception.
> Implement insertOrThrow of SQLiteStorageEngine interface

- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
- Set SQLite Error code into SQLException if error is SQLITE_CONSTRAINT
> Fixed couchbase-lite-java-core issue 655 Unique constraint violation

- src/main/java/com/couchbase/lite/JavaContext.java
- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngineFactory.java
Added getTempDir to JavaContext
https://github.com/couchbase/couchbase-lite-java-core/issues/719
https://github.com/couchbase/couchbase-lite-java-core/issues/720
> Support SQLite database and attachment rekey

- build.gradle
- settings.gradle
Changed according to https://github.com/couchbase/couchbase-lite-java-core/issues/847.
> Use new sqlite/sqlcipher native library packages

- build.gradle
Change couchbase-lite-java-forestdb dependency in build.gradle to only test.
> Make java-forestdb only test dependency

- src/main/java/com/couchbase/lite/JavaContext.java
- Implement getUserAgent() for Android platform.
- Added unit test for user agent.
Example: CouchbaseLite/1.2 (Java Mac OS X/x86_64 1.2.0/#000000)
> Fixed #909 - Formalize User-Agent value

- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
Changed from com.couchbase.lite.database.DatabasePlatformSupport to com.couchbase.lite.internal.database.DatabasePlatformSupport.
> Change according to renaming SQLite wrapper package

- build.gradle
- release/assembly.xml
- release/pom.xml
- release/settings.xml
- settings.gradle
- src/main/java/com/couchbase/lite/JavaContext.java
- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngineFactory.java
- src/main/java/com/couchbase/lite/util/SimpleLogger.java
- src/test/java/com/couchbase/test/lite/LiteTestCaseBase.java
https://github.com/couchbase/couchbase-lite-java-core/issues/1238
> Eliminated HttpClient dependency and other unused dependencies.

- release/assembly.xml
- release/pom.xml
Needs to add OkHttp and OkIo Jar files into Zip package
> fixed https://github.com/couchbase/couchbase-lite-java-core/issues/1294

- src/main/java/com/couchbase/lite/storage/JavaSQLiteStorageEngine.java
> Fixed https://github.com/couchbase/couchbase-lite-java-core/issues/1352

- CONTRIBUTING.md
Add link to [Couchbase Code of Conduct](https://www.couchbase.com/code-of-conduct).
> Update CONTRIBUTING.md w/ Code of Conduct

- build.gradle
Fix pom requirements for Maven Central upload
> CBD-2734 Add pom requirements for Maven upload

- src/main/java/com/couchbase/lite/Blob.java
- src/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
> Cherry-pick Iridium bugs to master

- src/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
Remove timeouts from OKHttp connection.
> Remove OKHttp timeouts #1913

- src/main/cpp/native_c4replicator.cc
- src/main/java/com/couchbase/lite/AbstractReplicator.java
- src/main/java/com/couchbase/lite/internal/core/C4Replicator.java
https://github.com/couchbase/couchbase-lite-android/issues/1912
Best guesses about what was wrong, without the opportunity to duplicate the issue.
> Attempted fix for replication crash (#1912)

- src/main/java/com/couchbase/lite/AbstractDatabase.java
- src/main/java/com/couchbase/lite/AbstractQuery.java
- src/main/java/com/couchbase/lite/LiveQuery.java
- src/main/java/com/couchbase/lite/Result.java
- src/main/java/com/couchbase/lite/ResultSet.java
In response to the CBSE, rework the code to be simpler and less likely to block the UI thread.
> Streamline LiveQuery

- src/main/java/com/couchbase/lite/AbstractReplicator.java
* Ported the fix from the Iridium branch.
* Canceled the pending scheduled retry before scheduling a new one.
* Added some more verbose logs.
Reference: https://github.com/couchbase/couchbase-lite-android/commit/b352b609ad292a327a8ab72913c7f270e457a57f
> Port the fix for multiple retry tasks scheduled in replicator (CB-131)

- src/main/java/com/couchbase/lite/AbstractReplicator.java
> Fix string format error in c4StatusChanged() (CBL-168)

- src/main/java/com/couchbase/lite/internal/replicator/AbstractCBLWebSocket.java
Fixed the regression bug that used the wrong option key.
> Fix replicator authentication not working (CBL-165)

- src/main/java/com/couchbase/lite/ConflictResolver.java
Fixes CBL-188
Change default conflict resolution so that deletion always wins.
> Default conflict resolution: deletion wins

- src/shared/test/java/com/couchbase/lite/DatabaseTest.java
> CBL-160: fix: test with special charatcters in windows

- src/main/java/com/couchbase/lite/NativeLibrary.java
- src/shared/main/cpp/native_c4.cc
- src/shared/main/cpp/native_c4blobstore.cc
- src/shared/main/cpp/native_c4document.cc
- src/shared/main/cpp/native_c4observer.cc
- src/shared/main/cpp/native_c4query.cc
- src/shared/main/cpp/native_c4queryenumerator.cc
- src/shared/main/cpp/native_c4replicator.cc
- src/shared/main/cpp/native_c4socket.cc
- src/shared/main/cpp/native_fleece.cc
- src/shared/main/cpp/native_glue.cc
- src/shared/test/java/com/couchbase/lite/DatabaseTest.java
- templates/CBLVersion.java
* fix: "error C7555: use of designated initializers requires at least '/std:c++latest'"
* suppress: Exception might ignore
* fix: library path corrected for windows
* fix: incompatible visual cpp commands.
* fix: include header which are necessary.
> CBL-160: fix: error with JNI files and gradle in windows

- src/main/java/com/couchbase/lite/MutableDocument.java
Resolved doc has empty body when its docId doesn't match the conflicted doc
> Fix for CBL-189

- src/main/java/com/couchbase/lite/NativeLibrary.java
* windows native library path corrected. only tested java in windows.
> CBL-160: fix: native libray path

- src/shared/main/java/com/couchbase/lite/AbstractQuery.java
- src/shared/test/java/com/couchbase/lite/BaseTest.java
- src/shared/test/java/com/couchbase/lite/ConcurrencyTest.java
- src/shared/test/java/com/couchbase/lite/DatabaseTest.java
- src/shared/test/java/com/couchbase/lite/LiveQueryTest.java
- src/shared/test/java/com/couchbase/lite/LoadTest.java
- src/shared/test/java/com/couchbase/lite/LogTest.java
- src/shared/test/java/com/couchbase/lite/QueryChangeTest.java
- src/shared/test/java/com/couchbase/lite/QueryTest.java
- src/shared/test/java/com/couchbase/lite/ResultTest.java
* Verified CBL-214 fix in Lite-Core that will auto closing statements in Query when the database is closed.
* Changed the tests accordingly.
* Used lamda syntax where possible.
> CBL-245 : Verify releasing query fix and change tests

- build.gradle
- scripts/prebuild_linux.sh
- src/main/java/com/couchbase/lite/NativeLibrary.java
* Added script/prebuild_linux.sh
* Updated build.gradle to support linux build
* Updated NativeLibrary.java
> CBL-159 : Build and test CBL-Java for linux

- src/shared/main/cpp/native_c4prediction.cc
* EE failure for initializer issue in visualcpp.
* CBL: 264
> CBL: 264: fix: c++ initializer issue in windows

- src/main/cpp/native_fleece.cc
- src/main/java/com/couchbase/lite/AbstractReplicator.java
- src/main/java/com/couchbase/lite/LiveQuery.java
- src/main/java/com/couchbase/lite/internal/core/C4Replicator.java
It is especially important, I believe, to check the changes in C4Replicator
> 2.6.2 release candidate

- src/shared/main/cpp/native_fleece.cc
- src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- src/shared/main/java/com/couchbase/lite/LiveQuery.java
- src/shared/main/java/com/couchbase/lite/internal/AbstractExecutionService.java
- src/shared/main/java/com/couchbase/lite/internal/ExecutionService.java
- src/shared/main/java/com/couchbase/lite/internal/core/C4Replicator.java
- src/shared/test/java/com/couchbase/lite/LiveQueryTest.java
- src/shared/test/java/com/couchbase/lite/ResultTest.java
Four separate commits:
- Normalize some formatting
- Hide the native methods in C4Replicator
- Fix broken LiveQuery tests
- CBL-478: Abort on RejectedExecution exceptions that are not caused by a closed Executor
> Four commits

- src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
As proposed in the amended spec, delay IDLE notifications until conflict resolution is complete
> CBL-487: delay idle notification while doing CCR

- build.gradle
- etc/jenkins/build_linux.sh
- etc/jenkins/build_macos.sh
- etc/jenkins/build_windows.bat
- etc/jenkins/extract_libs.sh
- etc/jenkins/publish.sh
- scripts/build_litecore.bat
- scripts/build_litecore.sh
- scripts/fetch_litecore.sh
Instruction for Jenkins to build CBL-Java: https://gist.github.com/pasin/a61b8d43aac96f3bd88048f5717ddaca
Some of the scripts might need to be changed if we restructure couchbase-lite-java repo.
> Add scripts for Jenkins and update POM info in build.gradle

- lib/src/shared/main/java/com/couchbase/lite/Blob.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4BlobReadStream.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4BlobStore.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4BlobWriteStream.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Database.java
- lib/src/shared/main/java/com/couchbase/lite/internal/utils/Preconditions.java
Rewrite Blob class for clarity and to improve performance.
The changes in `native_c4blobstore.cc` are exactly the changes in https://github.com/couchbase/couchbase-lite-java/pull/153, so there is probably no need to re-read them.
Most of the changes in other files are just sugar.  `Blob` is the big deal.
All of the tests pass for all of the variants.
> rewrite Blob

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
If both local and remote doc are deleted doc, automatically resolve by using the deleted remote doc.
> Fixed CBL-511 that resolves 2 deleted docs

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/Document.java
- lib/src/shared/main/java/com/couchbase/lite/utils/Fn.java
- lib/src/shared/test/java/com/couchbase/lite/BaseTest.java
- lib/src/shared/test/java/com/couchbase/lite/TestReplicatorChangeListener.java
I don't believe there are any changes in here that change behavior.
> Code cleanup

- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Replicator.java
Just some minor clean-up while getting tests working.
> Partial implementation of Pending IDs

- lib/src/shared/ce/java/com/couchbase/lite/Database.java
- lib/src/shared/test/java/com/couchbase/lite/DatabaseTest.java
Must be coordinated with the companion update in couchbase-lite-java-ee
> Add constructor with only database name parameter (CBL-230)

- lib/src/shared/main/cpp/native_c4replicator.cc
- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4ReplicationFilter.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Replicator.java
This fix allows the code to compile and all current tests to pass.  It does not implement the feature.
> Fix broken build

- etc/jenkins/README.md
- etc/jenkins/build_linux.sh
- etc/jenkins/build_macos.sh
- etc/jenkins/build_windows.bat
- etc/jenkins/extract_libs.sh
- etc/jenkins/publish.sh
- scripts/build_litecore.bat
- scripts/build_litecore.sh
- scripts/fetch_litecore.sh
- scripts/litecore_sha.ps1
- scripts/litecore_sha.sh
Updates based on working with new Jenkins jobs.
> MB-36681: Various build-script improvements for cbl-java

- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/Dictionary.java
- lib/src/shared/main/java/com/couchbase/lite/DictionaryInterface.java
- lib/src/shared/main/java/com/couchbase/lite/Document.java
- lib/src/shared/main/java/com/couchbase/lite/Result.java
> Make RevId available during replicator filtering

- lib/src/shared/main/java/com/couchbase/lite/LiveQuery.java
> CBL-234: Don't explicitly release previous ResultSet in LiveQuery

- lib/.gitignore
- lib/src/main/java/com/couchbase/lite/CouchbaseLite.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractQuery.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/Blob.java
- lib/src/shared/main/java/com/couchbase/lite/CouchbaseLiteException.java
- lib/src/shared/main/java/com/couchbase/lite/Document.java
- lib/src/shared/main/java/com/couchbase/lite/FileLogger.java
- lib/src/shared/main/java/com/couchbase/lite/Fleece.java
- lib/src/shared/main/java/com/couchbase/lite/ResultSet.java
- lib/src/shared/main/java/com/couchbase/lite/URLEndpoint.java
- lib/src/shared/main/java/com/couchbase/lite/internal/support/Log.java
- lib/src/shared/test/java/com/couchbase/lite/BaseTest.java
- lib/src/shared/test/java/com/couchbase/lite/LogTest.java
- lib/src/shared/test/java/com/couchbase/lite/PlatformTest.java
- lib/src/test/java/com/couchbase/lite/PlatformBaseTest.java
> Use standard error messages, where obvious

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/Query.java
Update the API doc for adding change listener API regarding the thread where the changes will be posted on.
> Update the API doc for adding change listener API

- lib/build.gradle
- Fixed javadoc generation failure.
- Added sourceJar and javadoc artifact.
> Fix build.gradle to generate javadoc and sources jar

- lib/src/shared/main/cpp/native_c4document.cc
- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabaseConfiguration.java
Two small fixes:
CBL-581: FLDoc leak
https://github.com/couchbase/couchbase-lite-android-ce/issues/31: Odd NPE in Database construction.
> CBL-581: Fix FLDoc leak

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/internal/support/Log.java
Fixes for two blocking bugs:
CBL-607: Force call to C4Log.setCallbackLevel
CBL-634: losing doc flags after conflict resolution
> Android mercury RC2

- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/internal/support/Log.java
Fix two Java blocking bugs
CBL-607: Force call to C4Log.setCallbackLevel
CBL-634: losing doc flags after conflict resolution
I'm afraid I don't know which RC this is...
> Java Mercury RC-n

- lib/src/shared/main/cpp/native_c4.cc
I think this is the right idea....  Please have a look?
This is just a preview: both sides of the ifdef compile, but I don't know if either runs.
> Add platform logger to avoid logging abort error

- lib/src/shared/main/cpp/native_c4replicator.cc
- lib/src/shared/main/java/com/couchbase/lite/AbstractDatabase.java
- lib/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Database.java
- lib/src/shared/main/java/com/couchbase/lite/internal/core/C4Replicator.java
- lib/src/shared/test/java/com/couchbase/lite/ReplicatorOfflineTest.java
- Ignore failing Replicator tests
- Remove socket factory in Local Replicator
- EE tests still failing
> Ignore failing Replicator tests

- lib/src/shared/main/cpp/native_c4.cc
Allow the internal API to initialize a domain that does not exist yet.
> CBL-733: Enable domain creation for internal API

- src/main/cpp/native_c4replicator.cc
* Cleanup document ended local references after using them
I have noticed from debugging that the local references may not get cleaned up immediately after the native method returns. As a result, there could be a lot of local references from a large set of document ended gets pilling up in the table to cause the overflow. This commit manually cleans up the local references after done using them.
Ref: CBSE-7597
* Fix accidentally remove the code to detach the current thread
> Cleanup document ended local references after using them (#165)
